[package]
name = "kosk"
version = "0.1.0"
edition = "2021"
default-run = "kosk"

[[bin]]
name = "sc2_test"
path = "src/bin/sc2_test.rs"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.5", features = ["derive"] }
eframe = { version = "0.33.3", default-features = false, features = ["glow"] }
egui = { version = "0.33.3", features = ["serde"] }
enigo = { version = "0.6.1", features = ["serde"] }
hidapi = "2.6.5"
notify = "6.1.1"
raw-window-handle = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_plain = "1.0.2"
strum = { version = "0.27", features = ["derive"] }
toml = "0.8"
windows-sys = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_Graphics_Dwm",
    "Win32_UI_WindowsAndMessaging",
] }

[features]
wgpu = ["eframe/wgpu"]
