scale_x = 36.0
scale_y = 40.0
transparent = true
stick_warp = 1.0
start_layout = "main"

[layouts]
main = "old_steam_controller_kb.toml"
qwerty = "qwerty.toml"
# symbols = "symbols.toml"
# numbers = "numbers.toml"

[debug]
show_stick_cursors = false
show_stick_bounds = false
show_hitboxes = false
