start_layout = "main"
stick_scale_x = 3.0
stick_scale_y = 2.5
stick_warp = 1.0
transparent = true
window_pos = [
    1186.6666259765625,
    681.34375,
]
scale_x = 30.0
scale_y = 32.0
event_debounce_ms = 300
event_debounce_repeat_ms = 55
stick_select_lock_ms = 100

[layouts]
main = "old_steam_controller_kb.toml"

[debug]
show_stick_cursors = false
show_hitboxes = false
show_stick_bounds = false

[text_input]
background_color = [
    255,
    255,
    255,
    255,
]
text_color = [
    0,
    0,
    0,
    255,
]
cursor_color = [
    0,
    0,
    0,
    255,
]
font_size = 22.0

[controller_map.MoveWindow]
faceRight = "switchState.menu"
options = "snapTopRight"
dpadDown = "nudgeDown"
faceLeft = "snapBottomLeft"
dpadUp = "nudgeUp"
faceBottom = "snapBottomRight"
dpadRight = "nudgeRight"
faceTop = "snapTopLeft"
dpadLeft = "nudgeLeft"

[controller_map.Keyboard]
dpadUp = "sendKey.up"
dpadDown = "sendKey.down"
faceTop = "toggleShift"
"options + faceTop" = "switchState.menu"
dpadRight = "sendKey.right"
"options + faceRight" = "switchState.textInput"
stickRight = "toggleAlt"
faceLeft = "sendKey.backspace"
"triggerLeft,threshold=40" = "sendKeyUnderLeftStick"
faceBottom = "sendKey.space"
"triggerRight,threshold=40" = "sendKeyUnderRightStick"
stickLeft = "toggleCtrl"
dpadLeft = "sendKey.left"

[controller_map.Menu]
faceRight = "switchState.keyboard"
dpadDown = "selectDown"
dpadUp = "selectUp"
faceBottom = "activate"

[controller_map.TextInput]
dpadRight = "moveCursorRight"
dpadUp = "switchState.keyboard"
dpadLeft = "moveCursorLeft"
