# Steam Controller keyboard layout
pad_x = 0.125
pad_y = 0.1
font_size = 24.0

[stick_bounds]
left = [
    { min = { x = 0.0, y = 0.0 }, max = { x = 6.95, y = 5.0 } },
    { min = { x = 0.0, y = 5.0 }, max = { x = 1.25, y = 6.2 } },
]
right = [
    { min = { x = 7.0, y = 0.0 }, max = { x = 14.0, y = 5.0 } },
    { min = { x = 10.4, y = 5.0 }, max = { x = 14.0, y = 6.2 } },
]

[[rows]]
indent = 0.0
height = 1.0

[[rows.keys]]
key = { normal = "1", shift = "!" }

[[rows.keys]]
key = { normal = "2", shift = "@" }

[[rows.keys]]
key = { normal = "3", shift = "#" }

[[rows.keys]]
key = { normal = "4", shift = "$" }

[[rows.keys]]
key = { normal = "5", shift = "%" }

[[rows.keys]]
key = { normal = "6", shift = "^" }
width = 1.2

[[rows.keys]]
key = "Skip"
width = 0.25

[[rows.keys]]
key = { normal = "7", shift = "&" }
width = 1.2

[[rows.keys]]
key = { normal = "8", shift = "*" }

[[rows.keys]]
key = { normal = "9", shift = "(" }

[[rows.keys]]
key = { normal = "0", shift = ")" }

[[rows.keys]]
key = { normal = "-", shift = "_" }

[[rows.keys]]
key = "Backspace"
display = { normal = "⌫", shift = "⌫" }

[[rows]]
indent = 0.0
height = 1.3

[[rows.keys]]
key = "q"
width = 1.4

[[rows.keys]]
key = "w"

[[rows.keys]]
key = "e"

[[rows.keys]]
key = "r"
width = 1.3

[[rows.keys]]
key = "t"
width = 1.6

[[rows.keys]]
key = "Skip"
width = 0.25

[[rows.keys]]
key = "y"
width = 1.6

[[rows.keys]]
key = "u"
width = 1.4

[[rows.keys]]
key = "i"

[[rows.keys]]
key = "o"

[[rows.keys]]
key = "p"
width = 1.4

[[rows]]
indent = 0.0
height = 1.1

[[rows.keys]]
key = "switchState.menu"
display = { normal = "⠿", shift = "⠿" }
width = 0.8

[[rows.keys]]
key = "a"

[[rows.keys]]
key = "s"

[[rows.keys]]
key = "d"

[[rows.keys]]
key = "f"

[[rows.keys]]
key = "g"
width = 1.4

[[rows.keys]]
key = "Skip"
width = 0.25

[[rows.keys]]
key = "h"
width = 1.5

[[rows.keys]]
key = "j"

[[rows.keys]]
key = "k"

[[rows.keys]]
key = "l"

[[rows.keys]]
key = "Return"
display = { normal = "⏎", shift = "⏎" }
width = 1.8

[[rows]]
indent = 0.0
height = 1.3

[[rows.keys]]
key = "toggleShift"
display = { normal = "⇧", shift = "⇧" }

[[rows.keys]]
key = { normal = ",", shift = "<" }

[[rows.keys]]
key = "z"

[[rows.keys]]
key = "x"

[[rows.keys]]
key = "c"

[[rows.keys]]
key = "v"
width = 1.2

[[rows.keys]]
key = "Skip"
width = 0.25

[[rows.keys]]
key = "b"
width = 1.2

[[rows.keys]]
key = "n"

[[rows.keys]]
key = "m"

[[rows.keys]]
key = { normal = "?", shift = "/" }

[[rows.keys]]
key = { normal = ".", shift = ">" }

[[rows.keys]]
key = "Shift"
display = { normal = "⇧", shift = "⇧" }

[[rows]]
indent = 0.0
height = 1.0

[[rows.keys]]
key = "Tab"
display = { normal = "⇥", shift = "⇥" }

[[rows.keys]]
key = " "
width = 9.1

[[rows.keys]]
key = "exit"
display = { normal = "Done", shift = "Done" }
width = 3.3

[[rows]]
indent = 0.0
height = 0.5

[[rows.keys]]
key = "switchState.textInput"
display = { normal = "i", shift = "i" }
width = 0.5
font_size = 16.0
