# Steam Controller keyboard layout
row_indents = [0.0, 0.0, 0.0, 0.0, 0.0]
row_heights = [1.0, 1.3, 1.1, 1.3, 1.0]
pad_x = 0.125
pad_y = 0.1
radius_mult = 1.125
font_size = 24.0

[stick_bounds]
left = [
    { min = { x = 0.0, y = 0.0 }, max = { x = 6.95, y = 5.0 } },
    { min = { x = 0.0, y = 5.0 }, max = { x = 1.25, y = 6.2 } },
]
right = [
    { min = { x = 7.0, y = 0.0 }, max = { x = 14.0, y = 5.0 } },
    { min = { x = 10.4, y = 5.0 }, max = { x = 14.0, y = 6.2 } },
]


[[keys]]
key = { normal = "1", shift = "!" }
pos = [0, 0]
width = 1.0

[[keys]]
key = { normal = "2", shift = "@" }
pos = [0, 1]
width = 1.0

[[keys]]
key = { normal = "3", shift = "#" }
pos = [0, 2]
width = 1.0

[[keys]]
key = { normal = "4", shift = "$" }
pos = [0, 3]
width = 1.0

[[keys]]
key = { normal = "5", shift = "%" }
pos = [0, 4]
width = 1.0

[[keys]]
key = { normal = "6", shift = "^" }
pos = [0, 5]
width = 1.2

# central gap — aligns with the split in rows 1-3
[[keys]]
key = "Skip"
pos = [0, 6]
width = 0.25

[[keys]]
key = { normal = "7", shift = "&" }
pos = [0, 7]
width = 1.2

[[keys]]
key = { normal = "8", shift = "*" }
pos = [0, 8]
width = 1.0

[[keys]]
key = { normal = "9", shift = "(" }
pos = [0, 9]
width = 1.0

[[keys]]
key = { normal = "0", shift = ")" }
pos = [0, 10]
width = 1.0

[[keys]]
key = { normal = "-", shift = "_" }
pos = [0, 11]
width = 1.0

[[keys]]
key = "Backspace"
display = { normal = "⌫", shift = "⌫" }
pos = [0, 12]
width = 1.0

[[keys]]
key = "q"
pos = [1, 0]
width = 1.4

[[keys]]
key = "w"
pos = [1, 1]
width = 1.0

[[keys]]
key = "e"
pos = [1, 2]
width = 1.0

[[keys]]
key = "r"
pos = [1, 3]
width = 1.3

[[keys]]
key = "t"
pos = [1, 4]
width = 1.6

[[keys]]
key = "Skip"
pos = [1, 5]
width = 0.25

[[keys]]
key = "y"
pos = [1, 6]
width = 1.6

[[keys]]
key = "u"
pos = [1, 7]
width = 1.4

[[keys]]
key = "i"
pos = [1, 8]
width = 1.0

[[keys]]
key = "o"
pos = [1, 9]
width = 1.0

[[keys]]
key = "p"
pos = [1, 10]
width = 1.4

[[keys]]
key = "Menu"
display = { normal = "⠿", shift = "⠿" }
pos = [2, 0]
width = 0.8

[[keys]]
key = "a"
pos = [2, 1]
width = 1.0

[[keys]]
key = "s"
pos = [2, 2]
width = 1.0

[[keys]]
key = "d"
pos = [2, 3]
width = 1.0

[[keys]]
key = "f"
pos = [2, 4]
width = 1.0

[[keys]]
key = "g"
pos = [2, 5]
width = 1.4

[[keys]]
key = "Skip"
pos = [2, 6]
width = 0.25

[[keys]]
key = "h"
pos = [2, 7]
width = 1.5

[[keys]]
key = "j"
pos = [2, 8]
width = 1.0

[[keys]]
key = "k"
pos = [2, 9]
width = 1.0

[[keys]]
key = "l"
pos = [2, 10]
width = 1.0

[[keys]]
key = "Return"
display = { normal = "⏎", shift = "⏎" }
pos = [2, 11]
width = 1.8

[[keys]]
key = "Shift"
display = { normal = "⇧", shift = "⇧" }
pos = [3, 0]
width = 1.0

[[keys]]
key = { normal = ",", shift = "<" }
pos = [3, 1]
width = 1.0

[[keys]]
key = "z"
pos = [3, 2]
width = 1.0

[[keys]]
key = "x"
pos = [3, 3]
width = 1.0

[[keys]]
key = "c"
pos = [3, 4]
width = 1.0

[[keys]]
key = "v"
pos = [3, 5]
width = 1.2

[[keys]]
key = "Skip"
pos = [3, 6]
width = 0.25

[[keys]]
key = "b"
pos = [3, 7]
width = 1.2

[[keys]]
key = "n"
pos = [3, 8]
width = 1.0

[[keys]]
key = "m"
pos = [3, 9]
width = 1.0

[[keys]]
key = { normal = "?", shift = "/" }
pos = [3, 10]
width = 1.0

[[keys]]
key = { normal = ".", shift = ">" }
pos = [3, 11]
width = 1.0

[[keys]]
key = "Shift"
display = { normal = "⇧", shift = "⇧" }
pos = [3, 12]
width = 1.0

[[keys]]
key = "Tab"
display = { normal = "⇥", shift = "⇥" }
pos = [4, 0]
width = 1.0

[[keys]]
key = " "
pos = [4, 1]
width = 9.1

[[keys]]
key = "Done"
display = { normal = "Done", shift = "Done" }
pos = [4, 2]
width = 3.3
