# Default QWERTY keyboard layout
pad_x = 0.125
pad_y = 0.1
font_size = 24.0

[[rows]]
indent = 0.0
height = 1.0

[[rows.items]]
key = { normal = "`", shift = "~" }

[[rows.items]]
key = { normal = "1", shift = "!" }

[[rows.items]]
key = { normal = "2", shift = "@" }

[[rows.items]]
key = { normal = "3", shift = "#" }

[[rows.items]]
key = { normal = "4", shift = "$" }

[[rows.items]]
key = { normal = "5", shift = "%" }

[[rows.items]]
key = { normal = "6", shift = "^" }

[[rows.items]]
key = { normal = "7", shift = "&" }

[[rows.items]]
key = { normal = "8", shift = "*" }

[[rows.items]]
key = { normal = "9", shift = "(" }

[[rows.items]]
key = { normal = "0", shift = ")" }

[[rows.items]]
key = { normal = "-", shift = "_" }

[[rows.items]]
key = { normal = "=", shift = "+" }

[[rows]]
indent = 1.0
height = 1.0

[[rows.items]]
key = "q"

[[rows.items]]
key = "w"

[[rows.items]]
key = "e"

[[rows.items]]
key = "r"

[[rows.items]]
key = "t"

[[rows.items]]
key = "y"

[[rows.items]]
key = "u"

[[rows.items]]
key = "i"

[[rows.items]]
key = "o"

[[rows.items]]
key = "p"

[[rows.items]]
key = { normal = "[", shift = "{" }

[[rows.items]]
key = { normal = "]", shift = "}" }

[[rows]]
indent = 1.5
height = 1.0

[[rows.items]]
key = "a"

[[rows.items]]
key = "s"

[[rows.items]]
key = "d"

[[rows.items]]
key = "f"

[[rows.items]]
key = "g"

[[rows.items]]
key = "h"

[[rows.items]]
key = "j"

[[rows.items]]
key = "k"

[[rows.items]]
key = "l"

[[rows.items]]
key = { normal = ";", shift = ":" }

[[rows.items]]
key = "Return"
width = 2.0

[[rows]]
indent = 0.0
height = 1.0

[[rows.items]]
key = "Shift"
width = 2.0

[[rows.items]]
key = "z"

[[rows.items]]
key = "x"

[[rows.items]]
key = "c"

[[rows.items]]
key = "v"

[[rows.items]]
key = "b"

[[rows.items]]
key = "n"

[[rows.items]]
key = "m"

[[rows.items]]
key = { normal = ",", shift = "<" }

[[rows.items]]
key = { normal = ".", shift = ">" }

[[rows.items]]
key = { normal = "/", shift = "?" }

[[rows]]
indent = 3.4
height = 1.0

[[rows.items]]
key = " "
width = 7.0
