# Default QWERTY keyboard layout
row_indents = [0.0, 36.25, 47.5, 0.0, 125.0]

[[keys]]
key = { normal = "`", shift = "~" }
row = 0
col = 0
width = 1.0

[[keys]]
key = { normal = "1", shift = "!" }
row = 0
col = 1
width = 1.0

[[keys]]
key = { normal = "2", shift = "@" }
row = 0
col = 2
width = 1.0

[[keys]]
key = { normal = "3", shift = "#" }
row = 0
col = 3
width = 1.0

[[keys]]
key = { normal = "4", shift = "$" }
row = 0
col = 4
width = 1.0

[[keys]]
key = { normal = "5", shift = "%" }
row = 0
col = 5
width = 1.0

[[keys]]
key = { normal = "6", shift = "^" }
row = 0
col = 6
width = 1.0

[[keys]]
key = { normal = "7", shift = "&" }
row = 0
col = 7
width = 1.0

[[keys]]
key = { normal = "8", shift = "*" }
row = 0
col = 8
width = 1.0

[[keys]]
key = { normal = "9", shift = "(" }
row = 0
col = 9
width = 1.0

[[keys]]
key = { normal = "0", shift = ")" }
row = 0
col = 10
width = 1.0

[[keys]]
key = { normal = "-", shift = "_" }
row = 0
col = 11
width = 1.0

[[keys]]
key = { normal = "=", shift = "+" }
row = 0
col = 12
width = 1.0

[[keys]]
key = "q"
row = 1
col = 0
width = 1.0

[[keys]]
key = "w"
row = 1
col = 1
width = 1.0

[[keys]]
key = "e"
row = 1
col = 2
width = 1.0

[[keys]]
key = "r"
row = 1
col = 3
width = 1.0

[[keys]]
key = "t"
row = 1
col = 4
width = 1.0

[[keys]]
key = "y"
row = 1
col = 5
width = 1.0

[[keys]]
key = "u"
row = 1
col = 6
width = 1.0

[[keys]]
key = "i"
row = 1
col = 7
width = 1.0

[[keys]]
key = "o"
row = 1
col = 8
width = 1.0

[[keys]]
key = "p"
row = 1
col = 9
width = 1.0

[[keys]]
key = { normal = "[", shift = "{" }
row = 1
col = 10
width = 1.0

[[keys]]
key = { normal = "]", shift = "}" }
row = 1
col = 11
width = 1.0

[[keys]]
key = "a"
row = 2
col = 0
width = 1.0

[[keys]]
key = "s"
row = 2
col = 1
width = 1.0

[[keys]]
key = "d"
row = 2
col = 2
width = 1.0

[[keys]]
key = "f"
row = 2
col = 3
width = 1.0

[[keys]]
key = "g"
row = 2
col = 4
width = 1.0

[[keys]]
key = "h"
row = 2
col = 5
width = 1.0

[[keys]]
key = "j"
row = 2
col = 6
width = 1.0

[[keys]]
key = "k"
row = 2
col = 7
width = 1.0

[[keys]]
key = "l"
row = 2
col = 8
width = 1.0

[[keys]]
key = { normal = ";", shift = ":" }
row = 2
col = 9
width = 1.0

[[keys]]
key = "Enter"
row = 2
col = 10
width = 2.0

[[keys]]
key = "Shift"
row = 3
col = 0
width = 2.0

[[keys]]
key = "z"
row = 3
col = 1
width = 1.0

[[keys]]
key = "x"
row = 3
col = 2
width = 1.0

[[keys]]
key = "c"
row = 3
col = 3
width = 1.0

[[keys]]
key = "v"
row = 3
col = 4
width = 1.0

[[keys]]
key = "b"
row = 3
col = 5
width = 1.0

[[keys]]
key = "n"
row = 3
col = 6
width = 1.0

[[keys]]
key = "m"
row = 3
col = 7
width = 1.0

[[keys]]
key = { normal = ",", shift = "<" }
row = 3
col = 8
width = 1.0

[[keys]]
key = { normal = ".", shift = ">" }
row = 3
col = 9
width = 1.0

[[keys]]
key = { normal = "/", shift = "?" }
row = 3
col = 10
width = 1.0

[[keys]]
key = " "
row = 4
col = 0
width = 7.0
